name: invest_ledger
description: 轻量级个人投资记账应用
publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # 状态管理
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # 数据库
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3

  # UI 组件
  material_color_utilities: ^0.11.1
  dynamic_color: ^1.7.0
  flex_color_scheme: ^8.2.0

  # 路由
  go_router: ^12.1.3

  # 图表
  fl_chart: ^0.65.0

  # 文件处理
  file_picker: ^8.0.0
  csv: ^5.0.2
  excel: ^2.1.0
  pdf: ^3.10.7

  # 工具库
  intl: ^0.18.1
  decimal: ^2.3.3
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  uuid: ^4.2.1
  crypto: ^3.0.3

  # 图标库
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  phosphor_flutter: ^2.0.1

  # 本地存储
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5

  # 网络请求
  http: ^1.1.0

  # 云数据库和同步
  supabase_flutter: ^2.5.6
  connectivity_plus: ^6.0.3

  # 环境变量管理
  flutter_dotenv: ^5.1.0

  # 版本管理
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5

  # 深度链接支持
  app_links: ^6.1.4

  # 文件下载和安装
  permission_handler: ^11.3.1
  open_file: ^3.5.7
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 代码生成
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - .env
    # - assets/images/
    # - assets/icons/

  # 当你添加实际的图片和图标文件时，取消注释上面的行


